[package]
name = "rpuc"
version = "0.2.0"
edition = "2021"
license = "MIT"
keywords = ["language", "glsl", "graphics", "shader", "rendering"]
repository = "https://github.com/markusmoenig/RPU.git"

[dependencies]
rpu = { path = "../rpu" }
clap = "4.5.4"
