[package]
name = "rpuc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpu = { path = "../rpu" }
clap = "4.5.4"
