[project]
name = "Warped Space Shooter"
version = "0.1.0"
start_scene = "Menu"

[window]
width = 272
height = 160
default_scale = 4.0
resize = "letterbox"

[meta]
bundle_id = "org.rpu.warped_space_shooter"
display_name = "Warped Space Shooter"
