[project]
name = "Sunnyland"
version = "0.1.0"
start_scene = "Main"

[window]
width = 320
height = 180
default_scale = 4.0
resize = "letterbox"

[debug]
physics = false

[meta]
bundle_id = "org.rpu.sunnyland"
display_name = "Sunnyland"
