[package]
name = "rpu-scenevm"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.22"
console_error_panic_hook = "0.1"
pollster.workspace = true
rpu-graphics = { path = "../rpu-graphics" }
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = ["Document", "DomRect", "Element", "EventTarget", "HtmlAudioElement", "HtmlCanvasElement", "HtmlElement", "KeyboardEvent", "MouseEvent", "WheelEvent", "Window", "CssStyleDeclaration", "console"] }

[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "tvos"), not(target_os = "ios")))'.dependencies]
rodio = "0.20"
winit.workspace = true

[target.'cfg(all(not(target_arch = "wasm32"), any(target_os = "tvos", target_os = "ios")))'.dependencies]
lewton = "0.10"
